name: test
on:
  pull_request:
    branches:
      - master
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v4
      - run: touch package-lock.json
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'
      - run: npm install
      - run: npm test
